### ISSUE TITLE
Missing sections in ReadMe.md leads to open questions

### ISSUE THREAD

**Issue by rstemmer** [jstrieb/urlpages#11]
When I came on this Repo, I was asking myself two questions and found no Answer:

- What is this (urlpages)?
- What problem does it solve?

I followed the link in the headline description but only landed inside a HTML/JS/CSS editor.

A short introduction that answers at least the the two questions would improve the ReadMe.

**Comment by jstrieb** [comment]
URL Pages simultaneously solves many problems and none. It was designed as a proof of concept that pages stored entirely in URLs actually work, rather than to solve a specific problem. Yet it can be used in a variety of different ways. It is my opinion that specifying what problem the project solves would be both disingenuous to the original aim, and would limit users' perceptions of the possible use cases.

Personally, I feel that the [About](https://github.com/jstrieb/urlpages#about) section of the README covers what the project is, with good support from the [How it works](https://github.com/jstrieb/urlpages#how-it-works) section. If you could be more specific about what those sections lack, I am open to improving them.

I await your response! In the meantime, I am closing this issue, and I may reopen it if you make a stronger case for the shortcomings of the README.

**Comment by rstemmer** [comment]
> Yet it can be used in a variety of different ways.

That's what I'd like to know - which ways? :)

For me it looks like a Cross-Site-Scripting technique or "bug" applied in a purposed way.
But how is this connected to the editor?
And what about Bookmarklet? Why do I need this?
So, do you have an "encoder" (Bookmarklet) that can clone encode any website as e.g. base64 code and a decoder called "main page" that then decodes the code that is an argument in the URL?

So to use the decode, I must serve the "main page"-tool somewhere?
When I understand it right, it can be used to share data as a base64 encoded (or similar) url+string, with the benefit that the receiver does not need to decode the base64-code because the decoder is called when calling the URL?

**Comment by jstrieb** [comment]
You are correct about the purpose in your last paragraph.

The editor is the same basic concept as 
- [CodePen](https://codepen.io/)
- [JSFiddle](https://jsfiddle.net/)

From the CodePen [About](https://codepen.io/about/) page:
> CodePen is a social development environment. At its heart, it allows you to write code in the browser, and see the results of it as you build. A useful and liberating online code editor for developers of any skill, and particularly empowering for people learning to code. We focus primarily on front-end languages like HTML, CSS, JavaScript

I feel that using the demo speaks for itself and makes the above use case for the editor fairly clear.

Beyond the editor, the "publication" capability can be used for anything that a static, single-page hosting site can be used for. That is enabled by allowing the "hosting" of arbitrary pages via the bookmarklet, or the creation of pages to "host" via the editor. If I made any modifications to the documentation, it would be to make this clearer, rather than to list explicit things that can be hosted. 

A brief list of things to host:
- Simple web forms (albeit non-critical ones where the data is not sensitive)
- Personal and informational web pages
- Temporary single-page sites that don't merit setting up hosting or dealing with domain names
- Copies of web pages that only you can access, but that you want to share
- Slightly modified versions of existing web pages
- Web pages in which there would otherwise be a concern of censorship by a web host
- Hacked-together web pages that you want to prototype and share with others

I feel that the [examples](https://github.com/jstrieb/urlpages#examples) in the README cover this type of web pages, while showing the possibilities rather than telling the user what they can do.

At this point, I feel that the README actually does address your questions, though it does it indirectly by demonstration rather than explicitly stating the answers outright.

**Comment by rstemmer** [comment]
> At this point, I feel that the README actually does address your questions, though it does it indirectly by demonstration rather than explicitly stating the answers outright.

That's the problem. The demonstration does not explain anything if you do not know where to look at.
Having an URL with some strange characters at the end it totaly usual.
Many web-applications encode their internal state in the URL to make it possible to share "the view" with other people.
Furthermore web browsers fade out everything after the first / of an URL.
And btw, nobody clicks on shorted URLs (here tinyurl.com) if he does not know what to expect :)

In fact, with this issue I only wanted to point out that the whole point of this project is invisible for visitors that are not familiar with Web-Technologies (I'm home at embedded systems).
I just followed a link posted on Hacker News with the expectation to see a nice Hack.
But all I found was a code-editor I saw a thousand times and an About-Section that told me nothing but every web-hoster would tell me - except the "No hosting"-Point which seems to be wrong in this case as well?

Of cause you do not have to update the README. I just saw some potential to make this little project be more accessible to other people and wanted to share it with you.

**Comment by jstrieb** [comment]
I think I understand your perspective a little better now, thanks for clarifying! I appreciate your willingness to go back and forth with me on this a little bit; it's helpful for me to see it from other users' point of view and I wanted to make sure I fully understood where you were coming from.

I will keep your perspective in-mind, and if others express similar concerns about the lack of project clarity in the documentation I'll be sure to make some changes!
