### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by ghost** [jstrieb/urlpages#14]
### Suggestions

- I think We should move it an orgnization site

- My other suggestion is to Make a Wiki for proper documentation

- My third and last suggestion is to embed css in html for saving no of requsts and improving loading content

**Comment by jstrieb** [comment]
For now, I am not interested in transferring to an organization site. However, if you feel you have good reasons for suggesting it, I could be convinced. Similarly, I don't foresee having enough documentation to merit setting up a wiki.

Regarding your last point: is that suggestion just generally to reduce the number of requests required for loading the editor? Or is it related to the editor reloading each time a key is pressed and the frame refreshes? Because if it's the latter, I am comfortable relying on browser caching. On the other hand, if it's the former, I feel that the pages are small enough that one extra request will have minimal impact.

I'm curious to hear your opinion, and await your response. In the meantime, I am closing the issue.

**Comment by ghost** [comment]
* In reponse to your answer regarding pont 3 my suggestion was to emed css in html *to load editor faster...*
* But if you want to call it from external sheet and enjoy browsing cache then I will suggest that  we should use **[JSDelive](https://www.jsdelivr.com/?docs=gh)** 
* The Reason here is that Github set **max-age header = 10 minutes** 
which is quite low But if we use Jsdelivr we can have a cache-Expiry of **7 Days**
* Again it is a sugggestion but chioce is yours
=> Thanks

**Comment by jstrieb** [comment]
Do you think that the editor doesn't load fast enough? Or are you suggesting improving it for the sake of making it faster?

**Comment by ghost** [comment]
It loads faster but There is always a need of improvement 
I appreciate your work but the my point here is that you if make css internal to call it through a global cdn service like Jsdelivr as I use in my own projects then Cache-header is set to 7 days instead of 10 minutes which on 2nd time loading make Editor blazing fast and it will save data also
I am newbie in web developing and keeps on researching and trying to make web fast In my own projects I use Jsdelivr and Then cache all scripts through service worker which in my case reduces send time loading speed from *`0.9`* seconds to **0.3** seconds
you are the developer and choice is yours I just tried to help it..

#### Disclaimer : I am Not associated to Jsdelivr to any of its projects.

**Comment by jstrieb** [comment]
Thanks for clarifying!

Currently it's easiest for me to manage everything if I keep it all on GitHub pages. I'm willing to sacrifice a little bit of the speed for ease of use on my side. Likewise, even though the separated files may make the page load slightly slower, I feel that it makes the project much easier to read and modify, so I'm going to leave it as-is. 

Thanks again for your input! I saw that you made a fork of the project with some changes -- I'll be sure to follow your progress so I can see where you end up taking the idea!

**Comment by aliglelo** [comment]
yes sure I will open a pull request after integrating all my ideas...

**Comment by aliglelo** [comment]
## Update
I have quickly(but roughly) worked out on my ideas 
and following are the results:
Project : [here](https://github.com/url-pages/url-pages.github.io)
Online : [here](url-pages.github.io)

**Comment by aliglelo** [comment]
And if you liked my work I would open pull request for UI..
