### ISSUE TITLE
Add Markdown vs HTML+CSS toggle?

### ISSUE THREAD

**Issue by ysharplanguage** [jstrieb/urlpages#22]
Very nice. I'm thinking maybe to have a simple toggle to propose some Markdown input in a (single) textarea as an alternative to the input from the (pair of) HTML+CSS textareas.

Sample minimal Markdown editor: [https://ysharp.io/markdown](https://ysharp.io/markdown)

**Comment by jstrieb** [comment]
Hi! Thanks for using the project, and apologies for the late response!

At the moment, integrating a markdown editor would make the code a little bit larger than I am comfortable with. It is important that the codebase stay small and auditable so that anyone using it can read through in one pass and be comfortable that they trust it.

I encourage you to make a fork with this functionality! If you do, I would be happy to link back to it on the main README.

Thanks again!
