### ISSUE TITLE
published URL larger than editor URL?

### ISSUE THREAD

**Issue by seekr** [jstrieb/urlpages#24]
hi @jstrieb is it possible that the editor version of the URL is smaller (in kb) than the published version? I've noticed that on a project I'm working on that editor weights 43k and published 63k...

ie. in the `examples/` embed-code.html is slightly smaller than embed-page.html

**Comment by jstrieb** [comment]
Thanks for using URL pages!

This is very interesting, and totally possible that the "published" URLs are longer. While I was working on [Link Lock](https://github.com/jstrieb/link-lock), I realized that oddities with `atob` and `btoa` in JavaScript that necessitated calls to `encodeURIComponent` could be avoided by using my own implementation of base64 encoding. These calls to `encodeURIComponent` are most likely a factor in the URL length disparity.

Since releasing Link Lock a little while ago, I have been thinking about the best way to remove unnecessary URI encoding while preserving backwards compatibility. I'm thinking doing of something like I do [in the Link Lock code](https://github.com/jstrieb/link-lock/blob/0acea1763717e2d181ef28e941ed363c2e25ec8e/create/create.js#L65), where the "published version" of URLs have a base64-encoded JSON object in the hash, which contains version information in addition to page data. That way if the decoder fails to decode valid JSON, it assumes it's using the original version. Likewise, future versions can have their own decoding schemes.

This is good motivation to give the code a much-needed tune-up. I will leave this issue open for now and investigate further over the weekend. Hopefully this resolves the issue of published URLs being longer. Thanks again for pointing this out, it is very helpful!

**Comment by jstrieb** [comment]
Finally got around to pushing the fixes to make the links slightly shorter. While I was at it, I restructured the code as a versioned API so that in the future I can add support for page compression, as well as any other features I have not thought of yet.

In most cases, the updated code seems to have reduced overall URL size. For example, a sampling of the pages in the `examples` directory shows:
```
$ du -h examples/*.html
348K    examples/embed-page-old.html
328K    examples/embed-page.html
256K    examples/food-blog-old.html
112K    examples/food-blog.html
372K    examples/nyt-old.html
268K    examples/nyt.html
252K    examples/project-page-old.html
268K    examples/project-page.html
```

Note that the `project-page.html` URL is larger because GitHub has changed their interface since I made the original link. 

I am now closing this issue. Thanks again!
