### ISSUE TITLE
multi-page sites (tree hierarchy)??

### ISSUE THREAD

**Issue by VatsaDev** [jstrieb/urlpages#27]
Hi, me again @vatsadev ! I got the preprocessors [working](https://js-labs.vercel.app/), [repo](https://github.com/VatsaDev/JsLabs/), and I am **Extremely** interested in multipage for url pages, but what does `multi-page sites (tree hierarchy)` mean? a few links or an explanation would be helpful.

**Comment by jstrieb** [comment]
Hi, thanks for reaching out about this! I saw your message on my contact form as well, but have been very busy and haven't had a chance to respond until now. Also, part of the reason that I wanted to wait is that this question deserves a response on the order of a blog post, rather than a reply here. But I'll give it a shot since you seem eager for an answer.

When you have URL Pages links, the entire page is contained in the URL. What this means is that if you have a site home page (call it `a`) and you want to link to some other URL page (`b`), then the entire content of the page `b` needs to be contained in its URL, all of which is contained in the page `a`. This means that linking to page `a` from page `b` is impossible, because then the entire contents of page `a` would need to be stored in page `b`, but page `b` is also entirely already stored in page `a`. This is very confusing, but hopefully clarifies why pages linking back to other pages is impossible.

The result is that a URL Pages website would have one page (a "root" of the tree) linking to other pages. These other pages could link to still more pages, but each child page must be fully contained in its parent page. The result is that the [webgraph](https://en.wikipedia.org/wiki/Webgraph) *must* be a directed, acyclic graph. This is exactly the definition of a [tree](https://en.wikipedia.org/wiki/Tree_(graph_theory)).

Hopefully this answers your question! Feel free to continue commenting with follow-ups, but in the meantime, I will close this issue.

**Comment by VatsaDev** [comment]
thanks for responding! the graph idea is pretty cool, but is there anyway in which a multifile mode is possible? I don't know if this sound incredulous or what, but if a person could make like multiple pages in one editor. like this -> 
![files](https://user-images.githubusercontent.com/71975550/110914494-75a5ab00-833c-11eb-9bfb-5a8ef8798265.PNG)
but like with urlpages instead of real files

**Comment by jstrieb** [comment]
The multifile mode would be a challenge, because the code would have to replace every instance of a file with an inlined version of the file's content. Even though it's theoretically possible, I don't think it makes sense for the majority of people who use URL Pages.

**Comment by VatsaDev** [comment]
ok
