### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by tobias-g1** [jstrieb/urlpages#6]
Nice site, I could see myself using this regularly for quick snippets, ideas, etc. 

Taking a look through, the functionality is great but could do with a nice slick UI. I've done quite a bit of design and am comfortable with writing the CSS, it looks like a fairly small project, but I like to get involved with projects like this. Overall, I was wondering if you'd like some help with the design and styling (if required) Something I did recently can be seen here:

![screely-1561898600446](https://user-images.githubusercontent.com/17148879/60400497-6aace600-9b6c-11e9-8868-963eaafb4dd3.png)

Let me know your thoughts. 

Thanks,
Tobias

**Comment by jackharrhy** [comment]
As noted in the README:

> Disclaimer
> This just becomes a toy if I am the only one hosting a running version of this repository. If you believe it has real potential, clone it or fork your own version that addresses any non-fundamental problems you have with it, and host your own. The only way this actually becomes robust is if there is no single point of failure (i.e. my GitHub Pages)

**Comment by jstrieb** [comment]
Hi Tobias,

Thanks for reaching out! I like the idea of having a better UI since I agree that right now it's sorely lacking.

In the interest of having as many implementations of this running as possible, I think the best course of action is to fork the code and make whatever improvements you see fit. Once you've fixed things up, make a pull request. If I like what I see, I'll merge it, otherwise it's just another (potentially better) version out there for people to use!

Thanks again for your interest! Can't wait to see what you come up with
