### ISSUE TITLE
Syntax Highlighting for HTML/CSS/JS textareas

### ISSUE THREAD

**Issue by silvia-odwyer** [jstrieb/urlpages#8]
Hey Jacob, 
I saw this on Hacker News, and think it's such an innovative idea; I'd love to help out with adding syntax highlighting to the textareas you have at the moment. 
Is this something you'd like to be implemented? We could use Codemirror or Prism for the syntax highlighting, and add various themes to the editor as a result.

**Comment by jstrieb** [comment]
Thanks for reaching out! I definitely hope to implement syntax highlighting in the text areas.

In the interest of having as many implementations of this running as possible, I think the best course of action is to fork the code and make whatever improvements you see fit. Once you've fixed things up, make a pull request. If I like what I see, I'll merge it, otherwise it's just another (potentially better) version out there for people to use!

In the meantime, I'm going to close this issue. Thanks again for your interest! I look forward to your pull request
